name: Tests Automatiques

# Ce workflow s'exécute à chaque push ou pull request sur n'importe quelle branche

on: [push, pull_request]

jobs:
  test:                                     # Nom du job
    runs-on: ubuntu-latest                  # Spécifie l’environnement de travail (machine virtuelle Ubuntu)

    steps:

      # Step 1: Cloner le code source du dépôt GitHub
      - name: Récupération du code
        uses: actions/checkout@v3

      # Step 2 : Installer Python 
      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3 : Installer les dépendances du projet
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # # Step 4 : Lancer les tests avec couverture
      - name: Exécuter les tests unitaires
        run: |
          python -m pytest --cov=src tests/        

